version: "3.5"

services:
  jekyll:
    build:
      context: ./
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
    command: bundle _2.1.4_ exec jekyll serve -H 0.0.0.0 -t

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - jekyll
